### ISSUE TITLE
[1pt] Choose assets - group task

### ISSUE THREAD

**Issue by iAmWaris97** [iAmWaris97/Delicious-Meals#19]
Choose images, text, icons, fonts.

**Comment by iAmWaris97** [comment]
Hi @MarcoAurelioAntonio,

As discussed during the Zoom meeting, and as we will have the header and footer, and main section of the page, the followings are the assets I suggest for the UI development:

- The image to use as the logo for the App: ==> 
![logo](https://user-images.githubusercontent.com/43011742/190216018-8c287438-492f-4a00-a8de-65706d7f930b.png)

- The image to use as an indicator for self-service: ==> 
![reception-bell-svgrepo-com](https://user-images.githubusercontent.com/43011742/190217513-10e0ac9f-3284-446f-bee1-8052a8c4da59.svg)

- Font for the entire App sections we will use is: ==> [https://fonts.google.com/specimen/Poppins](https://fonts.google.com/specimen/Poppins)

- Icon we will use for the like button is the heart icon from the fontawesome.

Thank you,

**Comment by MarcoAurelioAntonio** [comment]
Hi @iAmWaris97 , this is a great job looking for the assets before starting. I'm giving to conclude the task so we can be moving forward. 

## Happy coding!!
