### ISSUE TITLE
[0.5pt] Find external API - group task

### ISSUE THREAD

**Issue by iAmWaris97** [iAmWaris97/Delicious-Meals#20]
Find an API to base the development of the webapp around it. The API should allow you to
  - Get a list of items with a unique item id (or generate the unique id).
  - For a given item, get detailed information about it.
choose an APIs that doesn't need authentication. if you select an API that requires authentication, you should implement it on your own. Also, if you select an API that provides image resources your webapp will be more visual.

**Comment by iAmWaris97** [comment]
Hi @MarcoAurelioAntonio,

I have gone through different APIs we could use for the project, and after doing some research, I found the Meals API a good API to consume for our project.

The details of the API are as below:

- Link to the API documentation: ==> [MealDB API](https://www.themealdb.com/api.php)
- The API and site will always remain free.
- No authentication is required to consume the API.

- [ ] API Methods we will be using:
- Search meal by name: ==>  [www.themealdb.com/api/json/v1/1/search.php?s=Arrabiata](www.themealdb.com/api/json/v1/1/search.php?s=Arrabiata)
- List all meal categories: ==> [www.themealdb.com/api/json/v1/1/categories.php](www.themealdb.com/api/json/v1/1/categories.php)

**Comment by MarcoAurelioAntonio** [comment]
Hi @iAmWaris97 , this is a great job searching for everything we need before starting. I'm giving to conclude the task so we can be moving forward. 

## Happy coding!!
